# First Experiment

In [1]:
from implementations import *
from proj1_helpers import *

In [2]:
y_tr,tx_tr,ids_tr = load_csv_data('../all/train.csv')

In [3]:
_,tx_te,ids_te = load_csv_data('../all/test.csv')

In [30]:
weights,loss = least_squares(y_tr,tx_tr)

In [31]:
y_pred = predict_labels(weights,tx_te)

In [32]:
y_pred.shape

(568238,)

In [38]:
create_csv_submission(ids_te,y_pred,'least_squares_solved.csv')

# Only Derived Features or Primitive Features

In [3]:
from implementations import *
from proj1_helpers import *

In [2]:
y_tr,tx_tr,ids_tr = load_csv_data('../all/train.csv')

In [3]:
_,tx_te,ids_te = load_csv_data('../all/test.csv')

In [4]:
tx_tr_der = tx_tr[:,:15]
tx_tr_pri = tx_tr[:,15:]

In [5]:
tx_tr_der.shape

(250000, 15)

In [6]:
weights_der,loss_der = least_squares(y_tr,tx_tr_der)
weights_pri,loss_pri = least_squares(y_tr,tx_tr_pri)

In [7]:
y_pred_der = predict_labels(weights_der,tx_te[:,:15])
y_pred_pri = predict_labels(weights_pri,tx_te[:,15:])

In [8]:
y_pred_der.shape

(568238,)

In [9]:
create_csv_submission(ids_te,y_pred_der,'only_derived_features.csv')
create_csv_submission(ids_te,y_pred_pri,'only_primitives_features.csv')

In [10]:
# Use SGD with the mean of each feature as w_initial
w_initial = []
for i in range(0,tx_tr.shape[1]):
    w_initial.append(tx_tr[:,i][np.where(tx_tr[:,i] != -999)].mean())

In [40]:
# After 9999 iterations with gamma = 10e-8
w_initial = [ 3.7029055e-01,  5.65489100e+00,  5.02527572e-01, -2.17310225e+00,
       -3.93580998e+00, -2.57676902e-01, -3.42840900e+00,  7.11047980e-01,
        3.31146288e+00, -5.49211108e+00,  3.37708684e-01, -3.45348711e-01,
       -4.11275081e+00,  5.89253672e+00, -7.77042944e-03, -7.02905170e-03,
        4.59511012e+00, -1.67578736e-032,  1.50334830e-02,  5.72084780e+00,
       -1.80805659e-03,  1.25559763e+00, -4.16634272e-01,  1.97493110e+01,
       -9.82570321e+00, -9.84046189e+00,  2.06992554e+01, -4.19857993e+00,
       -4.19922223e+00, -1.59797593e+01]

In [49]:
weights,loss = least_squares_GD(y_tr,tx_tr,w_initial,10,0.1)

Gradient Descent(0/9): loss=103257.6568037911
Gradient Descent(1/9): loss=2035951908.2016077
Gradient Descent(2/9): loss=218929017685314.25
Gradient Descent(3/9): loss=3.2700157181973643e+25
Gradient Descent(4/9): loss=1.0753725912575386e+37
Gradient Descent(5/9): loss=3.536455527517423e+48
Gradient Descent(6/9): loss=1.1629939055628e+60
Gradient Descent(7/9): loss=3.824605777881643e+71
Gradient Descent(8/9): loss=1.2577546009690334e+83
Gradient Descent(9/9): loss=4.1362344987487475e+94


In [35]:
weights

array([ 3.37029055e-01,  5.65489100e+00,  5.02527572e-01, -2.17310225e+00,
       -3.93580998e+00, -2.57676902e-01, -3.42840900e+00,  7.11047980e-01,
        3.31146288e+00, -5.49211108e+00,  3.37708684e-01, -3.45348711e-01,
       -4.11275081e+00,  5.89253672e+00, -7.77042944e-03, -7.02905170e-03,
        4.59511012e+00, -1.67578736e-02,  1.50334830e-02,  5.72084780e+00,
       -1.80805659e-03,  1.25559763e+00, -4.16634272e-01,  1.97493110e+01,
       -9.82570321e+00, -9.84046189e+00,  2.06992554e+01, -4.19857993e+00,
       -4.19922223e+00, -1.59797593e+01])

In [ ]:
weights_

1


# Using MAE instead of MSE for outliers

In [1]:
from implementations import *
from proj1_helpers import *

In [2]:
y_tr,tx_tr,ids_tr = load_csv_data('../all/train.csv')

In [3]:
_,tx_te,ids_te = load_csv_data('../all/test.csv')

In [4]:
weights_mae,loss_mae = least_squares(y_tr,tx_tr,compute_mae)

In [5]:
y_pred_mae = predict_labels(weights_mae,tx_te)

In [7]:
create_csv_submission(ids_te,y_pred_mae,'least_squares_mae.csv')

# Experiment without indefinite values

In [10]:
# Feature columns with no indefinite values
columns = []
for i in range(0,tx_tr.shape[1]):
    unique, counts = np.unique(tx_tr[:,i], return_counts=True)
    if str(dict(zip(unique, counts)).get(-999)) == "None" :
        columns.append(i)

In [11]:
tx_tr_clean = tx_tr[:,columns]

In [13]:
weights_clean,loss_clean = least_squares(y_tr,tx_tr_clean)

In [15]:
y_pred_clean = predict_labels(weights_clean,tx_te[:,columns])

In [17]:
create_csv_submission(ids_te,y_pred_clean,'least_squares_clean.csv')

# Experiment using mean value instead of -999

In [7]:
from implementations import *
from proj1_helpers import *
from manipulate_data import *

In [104]:
y_tr,tx_tr,ids_tr = load_csv_data('../all/train.csv')

In [105]:
_,tx_te,ids_te = load_csv_data('../all/test.csv')

In [8]:
tx_tr_modified = np.copy(tx_tr)
tx_te_modified = np.copy(tx_te)

In [9]:
for i in range(0,tx_tr.shape[1]):
    feature_mean_tr = tx_tr[:,i][np.where(tx_tr[:,i] != -999)].mean()
    feature_mean_te = tx_tr[:,i][np.where(tx_tr[:,i] != -999)].mean()
    tx_tr_modified[:,i][tx_tr[:,i] == -999] = feature_mean_tr
    tx_te_modified[:,i][tx_te[:,i] == -999] = feature_mean_te

In [10]:
degree = 6
tx_tr_modified_with_polynomial = build_poly(tx_tr_modified,degree)
tx_te_modified_with_polynomial = build_poly(tx_te_modified,degree)

In [11]:
weights,loss = least_squares(y_tr,tx_tr_modified_with_polynomial)
y_pred = predict_labels(weights,tx_te_modified_with_polynomial)

In [85]:
filename = 'results/least_squares_implementation_Degree_6_mean_outlier_features.csv'
create_csv_submission(ids_te,y_pred,filename)

In [87]:
y_pred

array([-1., -1., -1., ...,  1.,  1., -1.])

In [99]:
print(tx_tr[0:20,22])

[2. 1. 1. 0. 0. 3. 2. 1. 0. 1. 0. 3. 1. 0. 0. 0. 1. 0. 0. 0.]


# Multi-model function

In [12]:
def multi_model_datasets_creation(y_tr,tx_tr,tx_te,feature_column_index,preprocess_func,preprocess_func_args,solve_function,solve_function_args):
    '''Return the prediction given a data processing function (like build_poly)'''
    categorization_values, counts = np.unique(tx_tr[:,feature_column_index], return_counts=True)
    num_models = len(categorization_values)
    
    tx_tr_array = list()
    y_tr_array = list()
    
    tx_te_array = list()
    
    tx_tr_preprocess_array = list()
    tx_te_preprocess_array = list()
    
    weights_array = list()
    loss_array = list()
    y_pred_array = list()
    idx_tr_array = list()
    idx_te_array = list()
    
    y_pred = np.zeros(tx_te.shape[0])
    
    for i in range(0,num_models):
        tx_tr_array.append(tx_tr[tx_tr[:, feature_column_index] == categorization_values[i], :])
        idx_tr_array.append(np.where(tx_tr[:, feature_column_index] == categorization_values[i]))
        y_tr_array.append(y_tr[idx_tr_array[i]])
        
        tx_te_array.append(tx_te[tx_te[:, feature_column_index] == categorization_values[i], :])
        idx_te_array.append(np.where(tx_te[:, feature_column_index] == categorization_values[i]))
        
        tx_tr_preprocess_array.append(preprocess_func(tx_tr_array[i],*preprocess_func_args))
        tx_te_preprocess_array.append(preprocess_func(tx_te_array[i],*preprocess_func_args))
        
        if(solve_function_args != None):
            weight,loss = solve_function(y_tr_array[i],tx_tr_preprocess_array[i],*solve_function_args)
            weights_array.append(weight)
            loss_array.append(loss)
        else:
            weight,loss = solve_function(y_tr_array[i],tx_tr_preprocess_array[i],*solve_function_args)
            weights_array.append(weight)
            loss_array.append(loss)
        
        y_pred_array.append(predict_labels(weights_array[i],tx_te_preprocess_array[i]))
    
        # we get the prediction back in the correct order
        
        y_pred[idx_te_array[i]] = y_pred_array[i]
    
    
    return y_pred

In [13]:
lambda_ = 10e-8
y_pred = multi_model_datasets_creation(y_tr,tx_tr_modified,tx_te_modified,22,build_poly,[6],ridge_regression,[lambda_])

In [14]:
y_pred.shape

(568238,)

In [15]:
filename = 'results/least_squares_implementation_Degree_6_mean_outlier_features_categorized.csv'
create_csv_submission(ids_te,y_pred,filename)

In [15]:
import numpy as np
k = 4
nb = 10
i = 1

np.where(np.fromfunction(lambda x: x % k, (nb,), dtype=int) == 0)


(array([0, 4, 8]),)